BEGIN;

DROP TABLE IF EXISTS
"users";

CREATE TABLE IF NOT EXISTS "users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text NOT NULL,
  "password" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

INSERT INTO "users" ("id","email","password") VALUES 
    (1, 'kinomatch@gmail.com', 'kinoxklcjvvb');


COMMIT;